buildscript: scripts/build
postinstall: scripts/postinstall.sh
package_target: deb
pip:
 - gunicorn
 - jinja2
dependencies:
 - libjpeg62
 - memcached
 - nginx
 - libxslt
 - libaio
 - libjpeg-turbo
 - libgpg-error-devel
 - libgcrypt-devel
 - libxml2-devel
 - libxslt1.1
 - libxslt1-dev
 - libjpeg-turbo8-dev
 - python-dev
 - libffi-dev
 - redis-server
