buildscript: scripts/build
postinstall: scripts/postinstall.sh
package_target: deb
pip:
 - gunicorn
 - jinja2
dependencies:
 - libjpeg62
 - memcached
 - nginx
 - redis-server
 - postgresql-server-dev-9.3
